image:
  name: irvinsaltedegg/eggyolk-build
  username: $DOCKER_HUB_USERNAME
  password: $DOCKER_HUB_PASSWORD
  email: $DOCKER_HUB_EMAIL

pipelines:
  branches:
    EW-17:
      - step:
          name: Clone package and build
          caches:
            - composer
          script:
            - git clone --branch="EW-17" git@bitbucket.org:irvinsaltedegg/eggyolk-package.git $BITBUCKET_CLONE_DIR/packages/project/src/Project
            - composer install --optimize-autoloader --no-interaction --prefer-dist --ignore-platform-reqs
          artifacts:
            - vendor/**
      - step:
          name: Deploy (Staging)
          deployment: staging
          script:
            - envoy run deploy --env=staging --edition=hk --host=$DEPLOY_HOST --user=$DEPLOY_USER --path=$DEPLOY_PATH --build=$BITBUCKET_BUILD_NUMBER --commit=$BITBUCKET_COMMIT --branch=$BITBUCKET_BRANCH --php='docker-compose exec -T app php' --dir=$BITBUCKET_CLONE_DIR
